### PR TITLE
quick fix for Windows path mismatch

### PR DESCRIPTION
**Pull request by kaid**
Corresponding regexp expressions won't recognize windows double backslashes in path strings, and here is a quick fix.

### CODE REVIEW

**Comment by AlexanderZaytsev** [comment]
Probably better to call `replace` in one place? Like this:

``` python
  def __init__(self, window, target_resource_name = None):
    self.window = window
    self.opened_file_name = self.window.active_view().file_name().replace('\\', '/')
```

**Comment by kaid** [comment]
there are other places using `self.opened_file_name` to find file, thus apply `replace` here will cause _file not found_ error.

**Comment by AlexanderZaytsev** [comment]
Ah, you right. Thanks again! :shipit:

**Comment by kaid** [comment]
thanks for merging :)

**Pull request merged**
